# Generated by Django 3.2.19 on 2023-06-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230622_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sutudios',
            new_name='Studios',
        ),
    ]
