version: '3.7'

volumes:
  pgdata:
    driver_opts:
      type: none
      device: $PWD/dbdata
      o: bind
services:
  nginx:
    image: nginx
    container_name: container.anime.nginx
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
      - ./nginx/log:/var/log/nginx
    depends_on:
      - web
  web:
    build: .
    container_name: container.anime.uwsgi
    command: uwsgi --ini /code/mainproject/django.ini
    volumes:
      - ./src:/code
    expose:
      - "8008"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: container.anime.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgresanimedb"
      POSTGRES_USER: "ryota"
      POSTGRES_PASSWORD: "animedb"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: postgres